<tool name="py3-flawfinder" version="2.0.19-3cdc958e442eef05e36bbd509a603d7e" revision="1">
  <client>
    <environment name="PY3_FLAWFINDER_BASE" default="/cvmfs/cms.cern.ch/el9_amd64_gcc13/external/py3-flawfinder/2.0.19-3cdc958e442eef05e36bbd509a603d7e"/>
  </client>
  <runtime name="PATH" value="$PY3_FLAWFINDER_BASE/bin" type="path"/>
</tool>
